# Generated by Django 3.2.9 on 2021-12-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0008_jsonfield_and_artifact'),
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='public', max_length=128)),
                ('rating', models.IntegerField()),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseSubmissionProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.process')),
                ('is_audited', models.BooleanField(default=None)),
                ('is_approved', models.BooleanField(default=None)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_processes', to='helloworld.response')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
    ]
