# Generated by Django 3.2.9 on 2021-12-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_response_responsesubmissionprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsesubmissionprocess',
            name='is_approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='responsesubmissionprocess',
            name='is_audited',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
